import esbuild, { type BuildOptions } from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/
`;

const prod = process.argv[2] === 'production';

const buildOptions: BuildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ['./src/entry-points/*.ts'],
  charset: 'utf8',
  bundle: true,
  target: 'esnext',
  platform: 'browser',
  minify: prod,
  // minify: false,
  // minifyWhitespace: true,
  sourcemap: prod ? false : 'inline',
  outdir: './chrome-extension/js',
};

const context = await esbuild.context(buildOptions);

if (prod) {
  try {
    await context.rebuild();
  } finally {
    process.exit(0);
  }
} else {
  await context.watch();
}
