/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/edit_dojo_after_designed.ts
  {
    const observer = new MutationObserver(function(mutationList, observer2) {
      if (!location.hash.startsWith("#dojo/myDojo/view/")) {
        return;
      }
      const playButton = document.querySelector('div[data-bind="visible:!myDojo.isOpen(),click:edit"]');
      if (playButton && playButton.style.display === "none") {
        playButton.style.display = "block";
      }
    });
    observer.observe(document.documentElement, { attributes: false, childList: true, subtree: true });
  }
})();
