/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/keep_current_page.ts
  {
    const match = document.cookie.match(/chapterId=(\d+)/);
    if (match) {
      const chapterId = match[1];
      const button = document.querySelector(`div#chapter_${chapterId}`);
      button.click();
    }
  }
})();
