/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/show_solution_button.ts
  {
    const observer = new MutationObserver(function(mutationList, observer2) {
      const solutionButton = document.querySelector("#solutionButton");
      if (!solutionButton) {
        return;
      }
      observer2.disconnect();
      solutionButton.style.display = "inline-block";
    });
    observer.observe(document.documentElement, { attributes: false, childList: true, subtree: true });
  }
})();
