/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/show_solution_button.ts
  {
    const observer = new MutationObserver(function(mutationList, observer2) {
      const solutionButton = document.querySelector("#solutionButton");
      if (!solutionButton) {
        return;
      }
      observer2.disconnect();
      solutionButton.style.display = "inline-block";
    });
    observer.observe(document.documentElement, { attributes: false, childList: true, subtree: true });
  }
})();
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiLi4vLi4vc3JjL2VudHJ5LXBvaW50cy9zaG93X3NvbHV0aW9uX2J1dHRvbi50cyJdLAogICJzb3VyY2VzQ29udGVudCI6IFsie1xyXG4gIGNvbnN0IG9ic2VydmVyID0gbmV3IE11dGF0aW9uT2JzZXJ2ZXIoZnVuY3Rpb24gKG11dGF0aW9uTGlzdCwgb2JzZXJ2ZXIpIHtcclxuICAgIGNvbnN0IHNvbHV0aW9uQnV0dG9uID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIiNzb2x1dGlvbkJ1dHRvblwiKTtcclxuICAgIGlmICghc29sdXRpb25CdXR0b24pIHtcclxuICAgICAgcmV0dXJuO1xyXG4gICAgfVxyXG4gICAgb2JzZXJ2ZXIuZGlzY29ubmVjdCgpO1xyXG4gICAgc29sdXRpb25CdXR0b24uc3R5bGUuZGlzcGxheSA9ICdpbmxpbmUtYmxvY2snO1xyXG4gIH0pO1xyXG4gIG9ic2VydmVyLm9ic2VydmUoZG9jdW1lbnQuZG9jdW1lbnRFbGVtZW50LCB7IGF0dHJpYnV0ZXM6IGZhbHNlLCBjaGlsZExpc3Q6IHRydWUsIHN1YnRyZWU6IHRydWUgfSk7XHJcbn0iXSwKICAibWFwcGluZ3MiOiAiOzs7Ozs7O0FBQUE7QUFDRSxVQUFNLFdBQVcsSUFBSSxpQkFBaUIsU0FBVSxjQUFjQSxXQUFVO0FBQ3RFLFlBQU0saUJBQWlCLFNBQVMsY0FBYyxpQkFBaUI7QUFDL0QsVUFBSSxDQUFDLGdCQUFnQjtBQUNuQjtBQUFBLE1BQ0Y7QUFDQSxNQUFBQSxVQUFTLFdBQVc7QUFDcEIscUJBQWUsTUFBTSxVQUFVO0FBQUEsSUFDakMsQ0FBQztBQUNELGFBQVMsUUFBUSxTQUFTLGlCQUFpQixFQUFFLFlBQVksT0FBTyxXQUFXLE1BQU0sU0FBUyxLQUFLLENBQUM7QUFBQSxFQUNsRzsiLAogICJuYW1lcyI6IFsib2JzZXJ2ZXIiXQp9Cg==
