/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/show_pixel_errors.ts
  {
    const interval = setInterval(() => {
      if (window.Turtle && window.Turtle.isCorrect) {
        const tableElement = document.getElementById("functionBar");
        if (!tableElement) {
          return;
        }
        clearInterval(interval);
        const tbodyElement = tableElement.querySelector("tbody");
        const newRow = tbodyElement.insertRow();
        const newCell = newRow.insertCell();
        newCell.textContent = "PixelErrors / permittedErrors: ";
        newCell.setAttribute("colspan", "3");
        window.Turtle.isCorrect = function(pixelErrors, permittedErrors) {
          newCell.textContent = `PixelErrors / permittedErrors: [${pixelErrors}/${permittedErrors}]`;
          if (pixelErrors >= permittedErrors) {
            newCell.style.color = "red";
          } else {
            newCell.style.color = "green";
          }
          return pixelErrors < permittedErrors && !Turtle.isAnswerBlank();
        };
      }
    }, 200);
  }
})();
