/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/show_maker_blocks_dojo.ts
  {
    const observer = new MutationObserver(function(mutationList, observer2) {
      const hintButton = document.querySelector("#hintButton");
      if (!hintButton) {
        return;
      }
      observer2.disconnect();
      const showMakerBlocksButton = hintButton.cloneNode(false);
      showMakerBlocksButton.textContent = "答案";
      showMakerBlocksButton.id = "showMakerBlocksButton";
      showMakerBlocksButton.title = "顯示武館的答案。";
      showMakerBlocksButton.addEventListener("click", () => {
        const xmlText = Turtle.level.json.makerBlocks;
        const xmlDom = Blockly.Xml.textToDom(`<xml>${xmlText}</xml>`);
        const workspace = Blockly.getMainWorkspace();
        workspace.clear();
        Blockly.Xml.domToWorkspace(workspace, xmlDom);
      });
      hintButton.parentElement.insertAdjacentElement("afterbegin", showMakerBlocksButton);
    });
    observer.observe(document.documentElement, { attributes: false, childList: true, subtree: true });
  }
})();
