/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/skip_checkin.ts
  {
    const checkinHash = "#checkin";
    if (window.location.hash === checkinHash) {
      window.location.hash = "#islands";
    }
  }
})();
