/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this extension
*/

(() => {
  // src/entry-points/skip_checkin.ts
  var checkinHash = "#checkin";
  if (window.location.hash === checkinHash) {
    window.location.hash = "#islands";
  }
})();
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiLi4vLi4vc3JjL2VudHJ5LXBvaW50cy9za2lwX2NoZWNraW4udHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImNvbnN0IGNoZWNraW5IYXNoID0gJyNjaGVja2luJztcblxuaWYgKHdpbmRvdy5sb2NhdGlvbi5oYXNoID09PSBjaGVja2luSGFzaCkge1xuICB3aW5kb3cubG9jYXRpb24uaGFzaCA9ICcjaXNsYW5kcyc7XG59XG4iXSwKICAibWFwcGluZ3MiOiAiOzs7Ozs7O0FBQUEsTUFBTSxjQUFjO0FBRXBCLE1BQUksT0FBTyxTQUFTLFNBQVMsYUFBYTtBQUN4QyxXQUFPLFNBQVMsT0FBTztBQUFBLEVBQ3pCOyIsCiAgIm5hbWVzIjogW10KfQo=
